---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api
resources:
- deployment.yaml
- hpa.yaml
- ingress.yaml
- netpol-egress.yaml
- netpol-ingress.yaml
- pdb.yaml
- service.yaml
