---
name: lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

env:
    KUSTOMIZE_VERSION: v5.1.0

jobs:
  lint-yaml:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        node: [20]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: "./k8s"
        config_file: "./.github/yamllint.config.yaml"

    - name: Set up Kustomize
      working-directory: k8s/staging
      run: |-
        curl -O -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/${{env.KUSTOMIZE_VERSION}}/kustomize_${{env.KUSTOMIZE_VERSION}}_linux_amd64.tar.gz
        tar xzf ./kustomize_${{env.KUSTOMIZE_VERSION}}_linux_amd64.tar.gz
        chmod u+x ./kustomize
    
    - name: Build the k8s manifests using Kustomize
      working-directory: k8s/staging
      run: |-
        ./kustomize build > staging-manifests.yaml

    - name: Scan k8s manifests with kube-linter
      uses: stackrox/kube-linter-action@v1.0.5
      with:
        directory: "./k8s/staging/staging-manifests.yaml"
        config: .github/kube-linter.yaml

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm ci

    - name: Lint JS
      run: npm run lint
